name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk
        pip install buildozer cython

    - name: Initialize buildozer
      run: |
        pip install buildozer
        buildozer init

    - name: Modify buildozer.spec
      run: |
        sed -i 's/^source.include_exts.*/source.include_exts = py,kv/' buildozer.spec
        sed -i 's/^requirements.*/requirements = python3,kivy/' buildozer.spec
        sed -i 's/^title.*/title = WebinarApp/' buildozer.spec
        sed -i 's/^package.name.*/package.name = webinarapp/' buildozer.spec
        sed -i 's/^package.domain.*/package.domain = org.example/' buildozer.spec
        sed -i 's/^# android.permissions.*/android.permissions = INTERNET/' buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: webinar-app-apk
        path: bin/*.apk
